'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {loadApp}=require('./harness'),FX=require('./fixtures'),{validateOperation}=require('../companion/operations.cjs');
const scope={sourceId:'t',fromDate:'1405/01/01',toDate:'1405/01/07'};
function app(){const a=loadApp();a.__context.atob=atob;a.extra=vm.runInContext('({receptionPartitions,fetchReceptionWindow,receptionCovers,receptionFlow,computeReceptionStats,SourceSnapshots,B2BRequests})',a.__context);vm.runInContext('renderOperationSnapshot=()=>{};recomputeDerived=()=>{};renderFileDots=()=>{};renderActiveTab=()=>{};',a.__context);return a;}
function payload(a,s,n=1,date=s.fromDate){const fields=a.SOURCE_DEFS.t.fields;const rows=Array.from({length:n},(_,i)=>({cardNo:'SYNTHETIC-'+date+'-'+i,admissionDate:date,createdAt:date+' 08:00',status:'در حال تعمیر',receptionist:'آزمایشی'}));return {scope:s,receivedAt:Date.now(),base64:FX.buildWorkbook([{name:'پذیرش',rows:[fields.map(f=>f.synonyms[0]),...rows.map(r=>fields.map(f=>r[f.key]??''))]}]).toString('base64')};}
test('report partitions stay disjoint and at most seven days, across month and year boundaries',()=>{const a=app(),p=a.extra.receptionPartitions('1405/06/28','1405/07/10');assert.equal(p.length,2);assert.equal(p[0].toDate,'1405/07/03');assert.equal(p[1].fromDate,'1405/07/04');assert.equal(p[1].toDate,'1405/07/10');const now=new Date('2026-10-02T08:00:00Z');for(const s of p)assert.doesNotThrow(()=>validateOperation(s,now));for(const bad of [{...p[0],fromDate:'1404/12/29'},{...p[0],toDate:'1405/07/10'},{...p[0],toDate:'1405/07/31'}])assert.throws(()=>validateOperation(bad,now),{code:'INVALID_SCOPE'});});
test('a capped 1000-row export is discarded and split, then all parts commit atomically',async()=>{const a=app();let writes=0;const calls=[];a.extra.SourceSnapshots.put=async()=>writes++;const result=await a.extra.fetchReceptionWindow(async(route,s)=>{assert.equal(route,'report');calls.push(s);assert.equal(writes,0);return payload(a,s,s.fromDate===scope.fromDate&&s.toDate===scope.toDate?1000:1);},scope);assert.equal(calls.length,3);assert.equal(result.count,2);assert.equal(writes,1);assert.equal(a.STATE.sources.t.meta.parts.length,2);assert.equal(a.STATE.sources.t.meta.fromDate,scope.fromDate);assert.equal(a.STATE.sources.t.records.length,2);});
test('later batch failure preserves the old complete report and writes nothing',async()=>{const a=app(),old={records:[{cardNo:'old'}]};a.STATE.sources.t=old;let writes=0,calls=0;a.extra.SourceSnapshots.put=async()=>writes++;await assert.rejects(a.extra.fetchReceptionWindow(async(route,s)=>{if(++calls>1)throw Error('synthetic interruption');return payload(a,s);},{...scope,toDate:'1405/01/14'}),/synthetic interruption/);assert.equal(writes,0);assert.equal(a.STATE.sources.t,old);});
test('a one-day cap or out-of-range export cannot masquerade as a complete window',async()=>{for(const capped of [true,false]){const a=app();let writes=0;a.extra.SourceSnapshots.put=async()=>writes++;await assert.rejects(a.extra.fetchReceptionWindow(async(route,s)=>payload(a,s,capped?1000:1,capped?s.fromDate:'1404/12/29'),{...scope,toDate:scope.fromDate}),capped?/۱۰۰۰/:/هم‌خوان نیست/);assert.equal(writes,0);}});
test('flow counts real releases and unique cards, and an uncovered day does not imply zero',()=>{const a=app(),rows=[{cardNo:'A',admissionDate:'1405/01/01',clearedDate:'1405/02/01',status:'ترخیص شده'},{cardNo:'A',admissionDate:'1405/01/01',clearedDate:'1405/02/01',status:'ترخیص شده'},{cardNo:'B',admissionDate:'1405/02/01',status:'در حال تعمیر'},{cardNo:'C',admissionDate:'1405/02/01',clearedDate:'1405/02/01',status:'انصرافی'}],s=a.extra.computeReceptionStats(rows,'1405/02/01'),flow=a.extra.receptionFlow(s,'1405/02/01');assert.equal(flow.admissions,3);assert.equal(flow.releasedToday,1);assert.deepEqual(Array.from(flow.months,m=>m.admissions),[1,2]);assert.deepEqual(Array.from(flow.months,m=>m.releases),[0,1]);const source={meta:{origin:'b2b',fromDate:'1405/01/01',toDate:'1405/02/01'}};assert.equal(a.extra.receptionCovers(source,'1405/02/02'),false);assert.equal(a.extra.receptionCovers(source,'1405/02/01'),true);});
test('nobat and operations transport requests share a serial queue',async()=>{const a=app();let active=0,max=0;a.__context.AbortSignal=AbortSignal;a.__context.fetch=async url=>{if(url.endsWith('session'))return {ok:true,json:async()=>({version:1,browser:'chrome',token:'synthetic'})};active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;return {ok:true,json:async()=>({message:'ok'})};};await Promise.all([a.extra.B2BRequests.request('sync',{}),a.extra.B2BRequests.request('report',{})]);assert.equal(max,1);});
